"""empty message

Revision ID: fd5c852c5bec
Revises: ed657e16ce20
Create Date: 2020-07-02 19:13:42.463082

"""

# revision identifiers, used by Alembic.
revision = 'fd5c852c5bec'
down_revision = 'ed657e16ce20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
